### PR TITLE
Refactor for supporting both legacy and next generation of Qubes OS builder

### PR DESCRIPTION
**Pull request by fepitre**
While writing the new Qubes OS builder, we integrated the content of the template-whonix repository into qubes-builderv2 repository directly to simplify the development. We are putting back refactored content for templates supporting both legacy and new Qubes builder into original repositories. Once this is merged into Whonix/qubes-template-whonix, we will adapt configuration file examples in qubes-builderv2 to use your key as maintainer for Whonix.

See:
- https://github.com/QubesOS/qubes-builderv2/pull/24
- https://github.com/QubesOS/qubes-builder-rpm/pull/120
- https://github.com/QubesOS/qubes-builder-debian/pull/63
- https://github.com/QubesOS/qubes-linux-template-builder/pull/25

### CODE REVIEW

**Comment by adrelanos** [comment]
Thank you!
Added a few minor commits on top.

**Comment by adrelanos** [comment]
Now added a more complex commit on top of it. That is adding the Kicksecure repository.

Adding the Kicksecure repository will be mandatory as soon as Whonix is based on Debian bookworm. Because Whonix is based on Kicksecure and by that time the repositories won't contain duplicate packages but be cleanly separated into packages from Kicksecure versus from Whonix.

This effectivly doesn't changes nothing because current Qubes-Whonix templates already contain both repositories.

**Comment by adrelanos** [comment]
Should I just copy/paste over these changes and send a pull request for qubes-builderv2 or would you like to do that?

**Comment by fepitre** [comment]
Everything related to Whonix should land in this repository that will be included like legacy builder. What changes do you need?

**Comment by adrelanos** [comment]
Copy/paste source:

* https://github.com/adrelanos/qubes-template-whonix/blob/master/whonix-gateway/04_install_qubes_post.sh
* https://github.com/adrelanos/qubes-template-whonix/blob/master/whonix-gateway/09_cleanup_post.sh

To target:

* https://github.com/QubesOS/qubes-builderv2/blob/main/qubesbuilder/plugins/template_whonix/whonix-gateway/04_install_qubes_post.sh
* https://github.com/QubesOS/qubes-builderv2/blob/main/qubesbuilder/plugins/template_whonix/whonix-gateway/09_cleanup_post.sh

**Comment by adrelanos** [comment]
I would be very much OK with having this repository here https://github.com/adrelanos/qubes-template-whonix being deprecated/deleted and replaced by folder there https://github.com/QubesOS/qubes-builderv2/blob/main/qubesbuilder/plugins/template_whonix

Having the code duplicated isn't great. We can only need to retain this repository here until Qubes legacy builder gets deprecated?

Meanwhile, until that happens if I make changes here, these need to be copied over from here (this repo) to there (Qubes builder v2)?

**Comment by fepitre** [comment]
Mer 21 déc 2022, à 19:06, Patrick Schleizer a écrit :
> 
> 
> I would be very much OK with having this repository here https://github.com/adrelanos/qubes-template-whonix being deprecated/deleted and replaced by folder there https://github.com/QubesOS/qubes-builderv2/blob/main/qubesbuilder/plugins/template_whonix
> 
> Having the code duplicated isn't great. We can only need to retain this repository here until Qubes legacy builder gets deprecated?
> 
https://github.com/QubesOS/qubes-builderv2/pull/24 this PR removes the content that is put back into original repositories. That's the purpose of the PR on template-whonix.

**Comment by adrelanos** [comment]
Understood. Thank you!

**Pull request merged**
